"""Pure conversation-floor logic for the AI voice panel.

Import nothing here that performs I/O. This package must stay replayable.
"""

from .events import (
    HUMAN,
    AgentProposal,
    AgentSpeechEnded,
    AgentSpeechStarted,
    Command,
    CueModerator,
    DuckSpeech,
    Event,
    HandsRaised,
    HumanSpeechEnded,
    HumanSpeechStarted,
    OperatorAction,
    OperatorCommand,
    RequestProposals,
    ResumeSpeech,
    Signals,
    StartSpeech,
    StateChanged,
    StopReason,
    StopSpeech,
    Tick,
    TranscriptUpdated,
    TurnYielded,
)
from .floor import AddressRole, CueReason, FloorController
from .personas import PanelCast, Persona
from .prompts import (
    GUARDRAILS,
    PROPOSAL_SCHEMA,
    build_system_prompt,
    build_turn_prompt,
    sanitise,
    stable_prefix,
)
from .scoring import (
    FloorConfig,
    floor_priority,
    interrupt_score,
    is_backchannel,
    may_interrupt,
)
from .state import (
    AgentState,
    Invitation,
    InvitationSource,
    PanelState,
    Proposal,
    Utterance,
)

__all__ = [
    "GUARDRAILS",
    "HUMAN",
    "PROPOSAL_SCHEMA",
    "AddressRole",
    "AgentProposal",
    "AgentSpeechEnded",
    "AgentSpeechStarted",
    "AgentState",
    "Command",
    "CueModerator",
    "CueReason",
    "DuckSpeech",
    "Event",
    "FloorConfig",
    "FloorController",
    "HandsRaised",
    "HumanSpeechEnded",
    "HumanSpeechStarted",
    "Invitation",
    "InvitationSource",
    "OperatorAction",
    "OperatorCommand",
    "PanelCast",
    "PanelState",
    "Persona",
    "Proposal",
    "RequestProposals",
    "ResumeSpeech",
    "Signals",
    "StartSpeech",
    "StateChanged",
    "StopReason",
    "StopSpeech",
    "Tick",
    "TranscriptUpdated",
    "TurnYielded",
    "Utterance",
    "build_system_prompt",
    "build_turn_prompt",
    "floor_priority",
    "interrupt_score",
    "is_backchannel",
    "may_interrupt",
    "sanitise",
    "stable_prefix",
]
